### ISSUE TITLE
Version 1.0.8 is broken in ext_localconf.php

### ISSUE THREAD

**Issue by andre-spindler** [ingeniumdesign/indexed_search_autocomplete#10]
Hello!

You current version is broken.

When checking the include of jquery, you create an instance of \TYPO3\CMS\Core\Configuration\ExtensionConfiguration and then directly access the key "get['disableJquerySource']" of your class object.
You should use "get('indexed_search_autocomplete ', 'disableJquerySource')" instead. 

TYPO3: 9.5.20

**Comment by felixmaechtle** [comment]
Hello,

thank you for reporting this issue!
It is fixed in the new version 1.0.9.
