### ISSUE TITLE
TER-Version 1.0.8 broken

### ISSUE THREAD

**Issue by kitzberger** [ingeniumdesign/indexed_search_autocomplete#11]
Seems like the folders of this extension on TER cannot be accessed for they're lacking the +x permission.

**Comment by ingeniumdesign** [comment]
the default typo3 permission is for folder 2775 and for Files 0644

**Comment by kitzberger** [comment]
Yeah, but the TER version doesn't have that ;-)

**Comment by ingeniumdesign** [comment]
fixed in Version 1.0.10
