### ISSUE TITLE
Installing via Composer doesn't work

### ISSUE THREAD

**Issue by RKlingler** [ingeniumdesign/indexed_search_autocomplete#13]
Hi,

I'm trying to install the latest version (1.0.10) through composer. However, `composer require id/indexed-search-autocomplete` gives me the following error message:

> Could not find a version of package id/indexed-search-autocomplete matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Side note:**
There is another package of the extension on Packagist:
https://packagist.org/packages/kitzberger/indexed-search-autocomplete
This one works. However, it seems to be a fork of the older version 1.0.8, which is not what I need.

**Comment by RKlingler** [comment]
I found that `composer require id/indexed-search-autocomplete:dev-master` works. It triggers some deprecation notices while installing though - I created a pull request for that.

Please consider creating a version tag and publishing the new version to Packagist, so that installing via composer and updating in the future works properly.

**Comment by RKlingler** [comment]
Hi @ingeniumdesign 

It's been a few months, but I would like to kindly ask if this issue could get some attention.

It would be much appreciated if you could accept the pull request and publish a new version to Packagist, so that the current version can be installed through composer without any workarounds.

**Comment by ingeniumdesign** [comment]
MR is done

**Comment by RKlingler** [comment]
Hi @ingeniumdesign 

This issue persists. I'm still getting the following error when trying to install via composer as described in the instructions:
`Could not find a version of package id/indexed-search-autocomplete matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.`

The reason is, that no releases have been published to packagist.

As far as I understand, tagging the releases via Git should be enough for packagist to make those versions available to composer. I added the tags in my fork repository: https://github.com/RKlingler/indexed_search_autocomplete
Unfortunatelly it's not possible to create pull requests for tags. So please add the version tags to this repo as well. At least for the latest version 1.0.11.

**Comment by ingeniumdesign** [comment]
Mhhh here in github is the info: Protected tags have been deprecated
