### ISSUE TITLE
require via composer fails

### ISSUE THREAD

**Issue by strophi** [ingeniumdesign/indexed_search_autocomplete#21]
I'm trying to install  yout extension via composer. It fails. 

Here is the composer error message

"Could not find a version of package id/indexed-search-autocomplete matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability."

After some research it seems that it is not tagged as stable. 

Could you please tag it as stable that composer won't complain?

thanx in advance

strophi

**Comment by jpmschuler** [comment]
For a "workaround" see https://stackoverflow.com/questions/76321761/install-extension-via-zip-in-typo3-composer-installation/76321889#76321889.

Please consider tagging some commits with a version to mark stable states.

**Comment by ingeniumdesign** [comment]
add the repositories
