### ISSUE TITLE
Delay before Ajax request...

### ISSUE THREAD

**Issue by stigfaerch** [ingeniumdesign/indexed_search_autocomplete#3]
Maybe it would be nice to have a delay before ajax requests are sent, so that no ajax requests are sent as long that there is active typing (which can be defined as milliseconds until no reaction).

**Comment by daCyberpunk** [comment]
you could use this file:
https://github.com/daCyberpunk/indexed_search_autocomplete/blob/master/Resources/Public/JavaScript/Indexed_search_autocomplete.js

**Comment by felixmaechtle** [comment]
Fixed :)
