### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by daCyberpunk** [ingeniumdesign/indexed_search_autocomplete#4]
Hi!

I was looking for this today and found it in TER. When i integrated it, a question came up.
Why you're making it so complicated, I mean...there might be a reason why you're implementing your own search and requests to db etc. 

by extending the original controller and just changing the search action, everthing would have been done. 
As a plus you can get the full power of indexed search in your autocpoplete request. 
also i adapted the js as it throws sometimes errors and it makes too many calls to the server which can lead to huge problems. ajax requests like thta always need to be debounced. 

Sorry, usually I am not a person interventing like that. But I am sharing what I changed within your extension (see my fork). Its not ready production code (there are still comments etc. and I did not adapt the fluid template for the word search, only for the links) but it works flawlessly now. 

let me know your thoughts, would be great. 

Anyway, thanks for sharing your ext to the world. :-D

**Comment by felixmaechtle** [comment]
Hey, 

that is a pretty good idea! But there is a problem for every user who already installed the extension: Due to the use of the original extension the path of the partials and the variable-names within those would be different. Thus an update would break an existing installation.

Do you have an idea how to avoid that?

**Comment by pquerner** [comment]
Not sure what you mean here. I'm not really in the topic. Usually if you make a new version out of it, people won't just update it. 1.0.6 to 2.0.0 with big red letters "BREAKING CHANGE" should take care of it.
Anyway. If someone is simply updating extensions without checking the changes its their fault, not yours.
