### ISSUE TITLE
inconsistent results

### ISSUE THREAD

**Issue by lstephanws** [ingeniumdesign/indexed_search_autocomplete#8]
Hello,

On our website, the results of the autocompletion do not seem to be consistent.
At times, autocompletion returns results and for other searches autocompletion returns no results (even though the search terms are well indexed).

Loïc Stéphan

**Comment by felixmaechtle** [comment]
Hello Stéphan,

could you send me a link (maybe per email in case you don't want to share it publicly) of your website so we can investigate the issue?

**Comment by ingeniumdesign** [comment]
Close after 1 Year. No Info.
