### ISSUE TITLE
template roothpaths don't seem to work

### ISSUE THREAD

**Issue by HenryAveMedi** [ingeniumdesign/indexed_search_autocomplete#9]
Hi there, i've been breaking my head for hours now, i want to redesign the link template, and nothing i do seems to work, changed the constants, change directly in setup, even used the tip of a closed issue here, but still, the extension uses the original templates
here a screenshot as proof that the setup.view shows my path, files are there, but no changes in the FE, please help, I want to avoid changing the original templates so that everything keeps working when i do ext updates
<img width="573" alt="image" src="https://user-images.githubusercontent.com/51093175/83980525-edaaf480-a916-11ea-93fe-42152176ede4.png">

**Comment by ingeniumdesign** [comment]
Hello Henry,

could you send me a link (maybe per email in case you don't want to share it publicly) of your website so we can investigate the issue?

**Comment by ingeniumdesign** [comment]
Close after 1 Year. No Infos.
